#cloud-config

package_update: true
package_upgrade: true
packages:
    - git
    - python-pip
    - python-swiftclient
runcmd:
    - git clone https://github.com/AdamOlevall/AirFoil.git
    - mv AirFoil home/ubuntu/AirFoil
    - chmod -R 777 home/ubuntu/AirFoil
    - cd home/ubuntu/AirFoil/naca_airfoil
    - pip install celery
    - sudo -H -u ubuntu bash -c "celery worker -A tasks &"